;; variable `package-activated-list'
(setq package-list
      '(all-the-icons
        all-the-icons-dired
        async
        auctex
        autopair
        avy
        browse-kill-ring
        buffer-move
        charmap
        color-moccur
        counsel
        counsel-projectile
        dash
        dashboard
        diminish
        disable-mouse
        dot-mode
        dumb-jump
        eclim
        epl
        evil
        evil-easymotion
        evil-extra-operator
        evil-indent-plus
        evil-lion
        evil-nerd-commenter
        evil-numbers
        evil-surround
        expand-region
        f
        flycheck
        fontawesome
        font-lock+
        framemove
        ggtags
        git-commit
        golden-ratio-scroll-screen
        goto-chg
        haskell-mode
        haskell-snippets
        hungry-delete
        hydra
        ivy
        latex-preview-pane
        let-alist
        linum-relative
        magit
        magit-popup
        markdown-mode
        memoize
        modalka
        multiple-cursors
        neotree
        org-bullets
        outorg
        outshine
        packed
        page-break-lines
        pkg-info
        popup
        projectile
        rainbow-delimiters
        rainbow-mode
        rich-minority
        s
        seq
        smart-mode-line
        smartparens
        swiper
        tabbar
        undo-tree
        which-key
        with-editor
        yasnippet
        yasnippet))
